# Generated by Django 5.1.7 on 2025-03-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=255)),
                (
                    "services",
                    models.TextField(help_text="Enter services separated by commas"),
                ),
                ("flyer_url", models.URLField()),
            ],
        ),
    ]
